# Claim Clash - Static web build for Claim-Clash.com (primary) + Claims-Clash.com (legacy)
#
# Usage (from project root):
#   .\scripts\build-web.ps1
#   .\scripts\build-web.ps1 -OutputDir "C:\path\to\web-dist"
#
# Output: web-dist/ folder ready to upload to Cloudflare Pages, Netlify, or GitHub Pages.
# AI calls are proxied by workers/site-gate.js at /api/ai (see workers/ai-proxy-handler.js).

param(
    [string]$OutputDir = "",
    [string]$SiteUrl = "https://claim-clash.com",
    [switch]$WithTestingKeys
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
if (-not (Test-Path (Join-Path $root "package.json"))) {
    Write-Error "Run this script from the claim-clash-tv project root."
}

if (-not $OutputDir) {
    $OutputDir = Join-Path $root "web-dist"
}

$versionPath = Join-Path $root "version.json"
$version = Get-Content $versionPath -Raw | ConvertFrom-Json
$pkg = Get-Content (Join-Path $root "package.json") -Raw | ConvertFrom-Json

Write-Host "=== Claim Clash Web Build (Claim-Clash.com) ===" -ForegroundColor Cyan

$profile = if ($WithTestingKeys) { 'Dev' } else { 'Release' }
& (Join-Path $PSScriptRoot "set-build-profile.ps1") -Profile $profile

$srcDir = Join-Path $root "src"
if (Test-Path $OutputDir) {
    Remove-Item $OutputDir -Recurse -Force
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

Copy-Item (Join-Path $srcDir "*") $OutputDir -Recurse -Force

$downloadDir = Join-Path $OutputDir "download"
New-Item -ItemType Directory -Path $downloadDir -Force | Out-Null
# Public (no password) Store / consumer pages under /download/
foreach ($publicPage in @('privacy-policy.html', 'support.html')) {
    $srcPage = Join-Path $srcDir $publicPage
    if (Test-Path $srcPage) {
        Copy-Item $srcPage (Join-Path $downloadDir $publicPage) -Force
    }
}

$brainFeedSrc = Join-Path $root "brain-feed\feed.json"
$brainFeedOutDir = Join-Path $OutputDir "brain-feed"
if (Test-Path $brainFeedSrc) {
    New-Item -ItemType Directory -Path $brainFeedOutDir -Force | Out-Null
    Copy-Item $brainFeedSrc (Join-Path $brainFeedOutDir "feed.json") -Force
}
# Same-origin relative path so Rule of 2 works on claim-clash.com and claims-clash.com alike.
$brainFeedUrl = if (Test-Path $brainFeedSrc) { '/brain-feed/feed.json' } else { $version.brainFeedUrl }

$installMeta = & (Join-Path $PSScriptRoot "stage-consumer-download.ps1") -OutputDir $OutputDir
$installAvailableJs = if ($installMeta.Available) { 'true' } else { 'false' }
$installUrlPath = if ($installMeta.PrimaryUrl) { $installMeta.PrimaryUrl } else { '/download/Claim-Clash-Setup.exe' }
$installFileName = if ($installMeta.PrimaryFile) { $installMeta.PrimaryFile } else { 'Claim-Clash-Setup.exe' }
$installKind = if ($installMeta.Kind) { $installMeta.Kind } else { 'none' }
$phaseLabel = if ($version.phase) { "$($pkg.version) $($version.phase.Trim())" } else { $pkg.version }

$webConfig = @"
// AUTO-GENERATED by scripts/build-web.ps1 — Claim-Clash.com web deploy config.
window.CLAIM_CLASH_WEB_CONFIG = {
    platform: 'web',
    siteUrl: '$SiteUrl',
    appPhase: 'Web',
    appVersion: '$($pkg.version)',
    feedbackEmail: '$($version.feedbackEmail)',
    privacyPolicyUrl: '$($version.privacyPolicyUrl)',
    brainFeedUrl: '$brainFeedUrl',
    brainVerifyPublicKeyHex: '$($version.brainVerifyPublicKeyHex)',
    useAiProxy: true,
    aiProxyPath: '/api/ai',
    consumerInstallAvailable: $installAvailableJs,
    consumerInstallVersion: '$phaseLabel',
    consumerInstallKind: '$installKind',
    consumerInstallUrl: '$SiteUrl$installUrlPath',
    consumerInstallFileName: '$installFileName',
    consumerInstallGuideUrl: '$SiteUrl/download/HOW-TO-INSTALL.txt'
};
"@

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText((Join-Path $OutputDir "web-config.js"), $webConfig, $utf8)

# Workers (site-gate.js) serves assets directly; SPA _redirects causes infinite-loop on wrangler deploy.

$headers = @"
/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()
"@
[System.IO.File]::WriteAllText((Join-Path $OutputDir "_headers"), $headers.Trim(), $utf8)

$robots = @"
User-agent: *
Disallow: /
"@
[System.IO.File]::WriteAllText((Join-Path $OutputDir "robots.txt"), $robots.Trim(), $utf8)

$deployReadme = @"
Claim Clash web-dist ($(Get-Date -Format 'yyyy-MM-dd HH:mm'))

PASSWORD-GATED DEPLOY (Claim-Clash.com)
  Full instructions: workers/DEPLOY.txt

Quick deploy:
  .\scripts\deploy-web.ps1

This bundle is served by workers/site-gate.js (developer password required).
AI calls use /api/ai behind the same session cookie.

Build profile: $(if ($WithTestingKeys) { 'Dev (pre-filled keys from scripts/alpha-keys.local.json)' } else { 'Release (no embedded keys)' })
Never use -WithTestingKeys for a public/Store release.
"@
[System.IO.File]::WriteAllText((Join-Path $OutputDir "DEPLOY.txt"), $deployReadme, $utf8)

Write-Host "`nWeb build complete:" -ForegroundColor Green
Write-Host "  $OutputDir"
Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "  1. Follow workers/DEPLOY.txt (KV namespace + password secrets)"
Write-Host "  2. Run: .\scripts\deploy-web.ps1"
Write-Host "  3. Local preview with gate: cd workers && npx wrangler dev"