# Sets Claim Clash build profile before packaging (dev / alpha / release).
# Generates src/build-profile.js consumed by index.html at runtime.
#
# Dev and Alpha keys are loaded from scripts/alpha-keys.local.json (gitignored).
# Copy alpha-keys.local.json.example and fill in your tester keys locally.
#
# Usage (from project root):
#   .\scripts\set-build-profile.ps1 -Profile Release   # main build: no embedded keys
#   .\scripts\set-build-profile.ps1 -Profile Dev       # beta-dev testing build with keys
#   .\scripts\set-build-profile.ps1 -Profile Alpha       # legacy alpha-tester zip builds

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('Alpha', 'Dev', 'Release')]
    [string]$Profile
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$outPath = Join-Path $root "src\build-profile.js"
$alphaKeysPath = Join-Path $PSScriptRoot "alpha-keys.local.json"

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Escape-JsString([string]$Value) {
    return ($Value -replace '\\', '\\\\' -replace "'", "\'")
}

if ($Profile -eq 'Alpha' -or $Profile -eq 'Dev') {
    if (-not (Test-Path $alphaKeysPath)) {
        Write-Error @"
$Profile build requires scripts/alpha-keys.local.json (gitignored).
Copy scripts/alpha-keys.local.json.example to scripts/alpha-keys.local.json and add tester API keys.
Never commit alpha-keys.local.json.
"@
    }
    $keys = Get-Content $alphaKeysPath -Raw | ConvertFrom-Json
    $gemini = Escape-JsString ([string]$keys.geminiApiKey)
    $anthropic = Escape-JsString ([string]$keys.anthropicApiKey)
    $openai = Escape-JsString ([string]$keys.openaiApiKey)
    $groq = Escape-JsString ([string]$keys.groqApiKey)
    $openrouter = Escape-JsString ([string]$keys.openrouterApiKey)
    $xai = Escape-JsString ([string]$keys.xaiApiKey)
    $profileSlug = if ($Profile -eq 'Alpha') { 'alpha' } else { 'dev' }
    $profileNote = if ($Profile -eq 'Alpha') {
        'Alpha (pre-filled tester keys from alpha-keys.local.json; never ship to Store or public release.)'
    } else {
        'Dev (pre-filled keys for beta-dev testing; never ship to Store or public release.)'
    }
    $buildStamp = (Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss')
    $content = @"
// AUTO-GENERATED by scripts/set-build-profile.ps1 — do not edit by hand.
// Profile: $profileNote
window.CLAIM_CLASH_BUILD_PROFILE = '$profileSlug';
window.CLAIM_CLASH_BUILD_STAMP = '$buildStamp';
window.ALPHA_TESTING_KEYS = {
    geminiApiKey: '$gemini',
    anthropicApiKey: '$anthropic',
    openaiApiKey: '$openai',
    groqApiKey: '$groq',
    openrouterApiKey: '$openrouter',
    xaiApiKey: '$xai'
};
"@
} else {
    $buildStamp = (Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss')
    $content = @"
// AUTO-GENERATED by scripts/set-build-profile.ps1 — do not edit by hand.
// Profile: Release (no embedded API keys.)
window.CLAIM_CLASH_BUILD_PROFILE = 'release';
window.CLAIM_CLASH_BUILD_STAMP = '$buildStamp';
window.ALPHA_TESTING_KEYS = {};
"@
}

Write-Utf8NoBom $outPath $content
Write-Host "Build profile set to $Profile -> $outPath" -ForegroundColor Green