# Sets Claim Clash build profile before packaging (alpha vs release).
# Generates src/build-profile.js consumed by index.html at runtime.
#
# Alpha keys are loaded from scripts/alpha-keys.local.json (gitignored).
# Copy alpha-keys.local.json.example and fill in your tester keys locally.
#
# Usage (from project root):
#   .\scripts\set-build-profile.ps1 -Profile Alpha
#   .\scripts\set-build-profile.ps1 -Profile Release

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('Alpha', 'Release')]
    [string]$Profile
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$outPath = Join-Path $root "src\build-profile.js"
$alphaKeysPath = Join-Path $PSScriptRoot "alpha-keys.local.json"

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Escape-JsString([string]$Value) {
    return ($Value -replace '\\', '\\\\' -replace "'", "\'")
}

if ($Profile -eq 'Alpha') {
    if (-not (Test-Path $alphaKeysPath)) {
        Write-Error @"
Alpha build requires scripts/alpha-keys.local.json (gitignored).
Copy scripts/alpha-keys.local.json.example to scripts/alpha-keys.local.json and add tester API keys.
Never commit alpha-keys.local.json.
"@
    }
    $keys = Get-Content $alphaKeysPath -Raw | ConvertFrom-Json
    $gemini = Escape-JsString ([string]$keys.geminiApiKey)
    $groq = Escape-JsString ([string]$keys.groqApiKey)
    $openrouter = Escape-JsString ([string]$keys.openrouterApiKey)
    $xai = Escape-JsString ([string]$keys.xaiApiKey)
    $content = @"
// AUTO-GENERATED by scripts/set-build-profile.ps1 — do not edit by hand.
// Profile: Alpha (pre-filled tester keys from alpha-keys.local.json; never ship to Store or public release.)
window.CLAIM_CLASH_BUILD_PROFILE = 'alpha';
window.ALPHA_TESTING_KEYS = {
    geminiApiKey: '$gemini',
    groqApiKey: '$groq',
    openrouterApiKey: '$openrouter',
    xaiApiKey: '$xai'
};
"@
} else {
    $content = @"
// AUTO-GENERATED by scripts/set-build-profile.ps1 — do not edit by hand.
// Profile: Release (no embedded API keys.)
window.CLAIM_CLASH_BUILD_PROFILE = 'release';
window.ALPHA_TESTING_KEYS = {};
"@
}

Write-Utf8NoBom $outPath $content
Write-Host "Build profile set to $Profile -> $outPath" -ForegroundColor Green