# Sync Claim Clash version from version.json across package metadata and UI.
# Version format: {major}.{minor}.{iteration}  e.g. 0.1.19
# Portable exe name: Claim Clash {version} {phase}.exe  e.g. Claim Clash 0.1.19 Alpha.exe
#
# Usage (from project root):
#   .\scripts\sync-version.ps1              # sync only
#   .\scripts\sync-version.ps1 -Increment   # bump iteration, then sync

param(
    [switch]$Increment
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

$versionFile = Join-Path $root "version.json"
if (-not (Test-Path $versionFile)) {
    Write-Error "Missing version.json at $versionFile"
}

$ver = Get-Content $versionFile -Raw | ConvertFrom-Json
if ($Increment) {
    $ver.iteration = [int]$ver.iteration + 1
    Write-Utf8NoBom $versionFile (($ver | ConvertTo-Json -Depth 3) + "`n")
    Write-Host "Iteration bumped to $($ver.iteration)" -ForegroundColor Cyan
}

$version = "{0}.{1}.{2}" -f $ver.major, $ver.minor, $ver.iteration
$phase = if ($ver.phase) { $ver.phase.Trim() } else { "Alpha" }
$versionLabel = if ($phase) { "$version $phase" } else { $version }
Write-Host "Syncing version $versionLabel ..." -ForegroundColor Yellow

function Update-ChangeLogs {
    param(
        [string]$Root,
        [string]$Version,
        [string]$Phase,
        [bool]$AddedIteration
    )

    $changelogPath = Join-Path $Root "CHANGE LOGS.txt"
    if (-not (Test-Path $changelogPath)) {
        $initLabel = if ($Phase) { "$Version $Phase" } else { $Version }
        $header = @"
Claim Clash Alpha - Change Logs
================================
Last updated: $(Get-Date -Format 'MMMM d, yyyy')
Current source version: $initLabel
Current packaged build in dist: (rebuild required)

Thank you for testing. Below is everything that changed in recent iterations.


"@
        Write-Utf8NoBom $changelogPath $header
    }

    $content = [System.IO.File]::ReadAllText($changelogPath)
    $today = Get-Date -Format "MMMM d, yyyy"
    $versionLabel = if ($Phase) { "$Version $Phase" } else { $Version }

    if ($content -match '(?m)^Last updated:.*$') {
        $content = $content -replace '(?m)^Last updated:.*$', "Last updated: $today"
    }
    if ($content -match '(?m)^Current source version:.*$') {
        $content = $content -replace '(?m)^Current source version:.*$', "Current source version: $versionLabel"
    }

    if ($AddedIteration) {
        $versionHeader = "VERSION $Version"
        if ($content -notmatch [regex]::Escape($versionHeader)) {
            $entry = @"

$versionHeader
--------------
(Document changes before packaging.)


"@
            if ($content -match '(?m)^FILENAME FORMAT') {
                $content = $content -replace '(?m)^(FILENAME FORMAT)', ($entry + '$1')
            } elseif ($content -match '(?m)^VERSION \d') {
                $content = $content -replace '(?m)^(VERSION \d)', ($entry + '$1')
            } else {
                $content = $content.TrimEnd() + "`n" + $entry
            }
        }
    }

    Write-Utf8NoBom $changelogPath $content
    Write-Host "Updated CHANGE LOGS.txt" -ForegroundColor Green
}

function Set-JsonVersion([string]$Path) {
    $text = [System.IO.File]::ReadAllText($Path)
    $text = $text -replace '(?m)^(\s*"version"\s*:\s*")[^"]+(")', "`${1}$version`${2}"
    Write-Utf8NoBom $Path $text
}

Set-JsonVersion (Join-Path $root "package.json")
Set-JsonVersion (Join-Path $root "src-tauri\tauri.conf.json")

$cargoPath = Join-Path $root "src-tauri\Cargo.toml"
$cargo = [System.IO.File]::ReadAllText($cargoPath)
$cargo = $cargo -replace '(?m)^version = ".*"$', "version = `"$version`""
Write-Utf8NoBom $cargoPath $cargo

$indexPath = Join-Path $root "src\index.html"
$index = [System.IO.File]::ReadAllText($indexPath)
$phase = if ($ver.phase) { $ver.phase.Trim() } else { "Alpha" }
$index = $index -replace 'const APP_VERSION = "[^"]+";', "const APP_VERSION = `"$version`";"
$index = $index -replace 'const APP_PHASE = "[^"]+";', "const APP_PHASE = `"$phase`";"
$feedbackEmail = if ($ver.feedbackEmail) { $ver.feedbackEmail.Trim() } else { "" }
$index = $index -replace 'const FEEDBACK_EMAIL = "[^"]*";', "const FEEDBACK_EMAIL = `"$feedbackEmail`";"
$privacyPolicyUrl = if ($ver.privacyPolicyUrl) { $ver.privacyPolicyUrl.Trim() } else { "" }
$index = $index -replace 'const PRIVACY_POLICY_URL = "[^"]*";', "const PRIVACY_POLICY_URL = `"$privacyPolicyUrl`";"
Write-Utf8NoBom $indexPath $index

function Update-BrainConfig {
    param(
        [string]$Root,
        [string]$FeedUrl,
        [string]$PublicKeyHex
    )

    $brainConfigPath = Join-Path $Root "src-tauri\src\brain_config.rs"
    $feed = if ($FeedUrl) { $FeedUrl.Trim() } else { "" }
    $key = if ($PublicKeyHex) { $PublicKeyHex.Trim() } else { "" }
    $content = @"
// AUTO-GENERATED by scripts/sync-version.ps1 — do not edit by hand.

pub const BRAIN_FEED_URL: &str = "$feed";
pub const BRAIN_VERIFY_PUBLIC_KEY_HEX: &str = "$key";
"@
    Write-Utf8NoBom $brainConfigPath $content
    Write-Host "Updated src-tauri/src/brain_config.rs" -ForegroundColor Green
}

$brainFeedUrl = if ($ver.brainFeedUrl) { $ver.brainFeedUrl.Trim() } else { "" }
$brainKey = if ($ver.brainVerifyPublicKeyHex) { $ver.brainVerifyPublicKeyHex.Trim() } else { "" }
Update-BrainConfig -Root $root -FeedUrl $brainFeedUrl -PublicKeyHex $brainKey

Update-ChangeLogs -Root $root -Version $version -Phase $phase -AddedIteration:$Increment.IsPresent

Write-Host "Version $version synced to package.json, tauri.conf.json, Cargo.toml, index.html, and brain_config.rs" -ForegroundColor Green