// AUTO-GENERATED by scripts/sync-version.ps1 â€” do not edit by hand.

pub const BRAIN_FEED_URL: &str = "https://raw.githubusercontent.com/memento-mori1984/claim-clash-tv/master/brain-feed/feed.json";
pub const BRAIN_VERIFY_PUBLIC_KEY_HEX: &str = "ac589a76a04a9b87cba69c91b8bdd3675cfbdd9830da330ad933ceea237fadfb";