// AUTO-GENERATED by scripts/set-build-profile.ps1 â€” do not edit by hand.
// Profile: Release (no embedded API keys.)
window.CLAIM_CLASH_BUILD_PROFILE = 'release';
window.CLAIM_CLASH_BUILD_STAMP = '20260711-201117';
window.ALPHA_TESTING_KEYS = {};